//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class payroll_dbEntities : DbContext
    {
        public payroll_dbEntities()
            : base("name=payroll_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_bankdetails> tbl_bankdetails { get; set; }
        public virtual DbSet<tbl_department> tbl_department { get; set; }
        public virtual DbSet<tbl_designation> tbl_designation { get; set; }
        public virtual DbSet<tbl_employee> tbl_employee { get; set; }
        public virtual DbSet<tbl_healthinsurance> tbl_healthinsurance { get; set; }
        public virtual DbSet<tbl_holiday> tbl_holiday { get; set; }
        public virtual DbSet<tbl_millUnit> tbl_millUnit { get; set; }
        public virtual DbSet<tbl_nationality> tbl_nationality { get; set; }
        public virtual DbSet<tbl_reasons> tbl_reasons { get; set; }
        public virtual DbSet<tbl_religion> tbl_religion { get; set; }
        public virtual DbSet<tbl_subdepartment> tbl_subdepartment { get; set; }
        public virtual DbSet<tbl_terminal> tbl_terminal { get; set; }
        public virtual DbSet<tbl_timing> tbl_timing { get; set; }
        public virtual DbSet<tbl_timingGroup> tbl_timingGroup { get; set; }
        public virtual DbSet<tbl_user> tbl_user { get; set; }
        public virtual DbSet<tbl_vehicledetention> tbl_vehicledetention { get; set; }
    }
}
