//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_timing
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_timing()
        {
            this.tbl_employee = new HashSet<tbl_employee>();
        }
    
        public int time_id { get; set; }
        public string timing { get; set; }
        public string timefrom { get; set; }
        public string timeupto { get; set; }
        public string outupto { get; set; }
        public string dutyhours { get; set; }
        public string shifttype { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_employee> tbl_employee { get; set; }
    }
}
