//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_employee
    {
        public int emp_id { get; set; }
        public string emp_name { get; set; }
        public string emp_father_name { get; set; }
        public string emp_address { get; set; }
        public string emp_email { get; set; }
        public int emp_mobile_no { get; set; }
        public int emp_nic { get; set; }
        public Nullable<int> nationality_id { get; set; }
        public Nullable<System.DateTime> emp_dob { get; set; }
        public int emp_age { get; set; }
        public string emp_martial_status { get; set; }
        public Nullable<int> religion_id { get; set; }
        public string emp_gender { get; set; }
        public Nullable<int> unit_id { get; set; }
        public Nullable<int> dept_id { get; set; }
        public Nullable<int> sdept_id { get; set; }
        public Nullable<int> desig_id { get; set; }
        public Nullable<int> tg_id { get; set; }
        public string emp_type { get; set; }
        public Nullable<System.DateTime> emp_appt_date { get; set; }
        public int emp_salary { get; set; }
        public string emp_wage_cat { get; set; }
        public Nullable<int> time_id { get; set; }
        public string emp_restday { get; set; }
        public string emp_reportto { get; set; }
        public string emp_contract_service { get; set; }
        public string emp_ot { get; set; }
        public string emp_onshift { get; set; }
        public string emp_colony { get; set; }
        public string emp_inst_type { get; set; }
        public string emp_inst_title { get; set; }
        public string emp_inst_name { get; set; }
        public string emp_inst_passing_g { get; set; }
        public string emp_inst_passing_yr { get; set; }
        public string emp_last_company { get; set; }
        public string emp_last_position { get; set; }
        public string emp_experince { get; set; }
        public string emp_last_salary { get; set; }
        public Nullable<int> health_id { get; set; }
        public Nullable<int> veh_id { get; set; }
        public string emp_incometax { get; set; }
        public string emp_ntn_no { get; set; }
        public string emp_eobi_no { get; set; }
        public string emp_sessi_no { get; set; }
        public string emp_gi_no { get; set; }
        public string emp_graduity { get; set; }
        public string emp_pf { get; set; }
        public Nullable<int> emp_ref_no { get; set; }
        public string emp_ref_name { get; set; }
        public int emp_ref_mob { get; set; }
        public string emp_ref_email { get; set; }
        public Nullable<int> bank_id { get; set; }
        public string emp_acct_no { get; set; }
        public string emp_acct_name { get; set; }
        public string emp_iban_no { get; set; }
    
        public virtual tbl_department tbl_department { get; set; }
        public virtual tbl_designation tbl_designation { get; set; }
        public virtual tbl_healthinsurance tbl_healthinsurance { get; set; }
        public virtual tbl_millUnit tbl_millUnit { get; set; }
        public virtual tbl_nationality tbl_nationality { get; set; }
        public virtual tbl_subdepartment tbl_subdepartment { get; set; }
        public virtual tbl_timing tbl_timing { get; set; }
        public virtual tbl_timingGroup tbl_timingGroup { get; set; }
        public virtual tbl_vehicledetention tbl_vehicledetention { get; set; }
    }
}
