//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_holiday
    {
        public int h_id { get; set; }
        public string h_name { get; set; }
        public Nullable<System.DateTime> h_date { get; set; }
        public string h_otrates { get; set; }
    }
}
