//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_bankdetails
    {
        public int bank_id { get; set; }
        public string bank_name { get; set; }
        public string branch_name { get; set; }
        public int branch_code { get; set; }
        public string address { get; set; }
        public string country { get; set; }
        public string currency { get; set; }
    }
}
